### ISSUE TITLE
Report Checklist

### ISSUE THREAD

**Issue by i3anaan** [wandernauta/viskell#110]
**Chapters**
- [ ] Summary
- [x] Introduction
- [ ] Process and tools
  - [x] Tasks and responsibilities
  - [x] Code tools
  - [ ] Process tools
- [x] Requirements
  - [x] Target user
  - [x] Visual requirements
  - [x] Functional Requirements
  - [x] Multi-touch requirements
- [ ] Design
  - [x] Languages and libraries
  - [x] High-level architecture
  - [x] Backend architecture
- [ ] Implementation
  - [ ] Front end
    - [ ] Graphical design
    - [ ] Behaviour and interaction design
  - [x] Back end
- [ ] Test plan
- [x] Evaluation
- [x] Conclusions
- [x] Recommendations

**Appendices**
- [ ] User manual

**Diagrams**
Add useful UML diagrams where possible. The example reports on BlackBoard suggest that at least some teachers like to see them in reports.

**Comment by jjkester** [comment]
Updated list

**Comment by jjkester** [comment]
Checked off target user

**Comment by jjkester** [comment]
Checked off high level architecture
